correctness:
	g++ -o correctness correctness.cpp SSTable.cpp Entry.cpp SearchResult.cpp SkipList.cpp SSTableId.cpp LevelZero.cpp Utility.cpp LevelNonZero.cpp DiskStorage.cpp KVStore.cpp -std=c++17
persistence:
	g++ -o persistence persistence.cpp SSTable.cpp Entry.cpp SearchResult.cpp SkipList.cpp SSTableId.cpp LevelZero.cpp Utility.cpp LevelNonZero.cpp DiskStorage.cpp KVStore.cpp -std=c++17
